repos:
  # Use pre-commit repo, v3.4.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
        stages: [ commit, push ]
      # Simply check whether files parse as valid python.
      - id: check-ast
        stages: [ commit ]

    # Use locally installed hooks
  - repo: local

    hooks:
      - id: black-format-staged
        name: black
        entry: poetry
        args:
          - run
          - black
        language: system
        types: [ python ]
        stages: [ commit ]

      - id: mypy-check-staged
        name: mypy
        entry: poetry
        args:
          - run
          - mypy
          - rss_parser
        language: system
        stages: [ push ]

      - id: ruff-check-global
        name: ruff
        entry: poetry
        args:
          - run
          - ruff
          - check
        language: system
        types: [ python ]
        stages: [ commit, push ]