name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  # TODO: Only on CI success

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build sdist and wheel
        run: uv build

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.pypi_password }}
